#!/bin/bash
# Initialize refine-backlog system in a repository

set -euo pipefail

# Determine script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

# =============================================================================
# HELP
# =============================================================================

show_help() {
  cat <<'EOF'
Initialize the Backlog Refinement System in your repository

USAGE:
  ./init-refine-backlog.sh [options]

OPTIONS:
  --help              Show this help message
  --repo OWNER/REPO   GitHub repository (auto-detected if omitted)
  --token TOKEN       GitHub API token (can be set via env or config)
  --api-key KEY       Anthropic API key (can be set via env or config)
  --install-skill     Install skill to ~/.claude/commands/ (default: true)
  --no-install-skill  Skip skill installation

EXAMPLE:
  ./init-refine-backlog.sh --repo myorg/myrepo --token ghp_xxx --api-key sk-ant-xxx

WHAT THIS SCRIPT DOES:
  1. Validates git repository
  2. Creates ~/.local/refine-backlog.conf (if needed)
  3. Creates .local/bin/refine-backlog symlink to refine-backlog.sh
  4. Initializes refinement-log.json in repo root
  5. Installs Claude skill to ~/.claude/commands/refine-backlog.md
  6. Adds entries to .gitignore

NEXT STEPS:
  1. Edit ~/.local/refine-backlog.conf to add missing tokens
  2. Run: refine-backlog check
  3. Run: refine-backlog refine --all

EOF
}

# =============================================================================
# UTILITIES
# =============================================================================

log_info() {
  echo -e "${BLUE}ℹ${NC} $*"
}

log_success() {
  echo -e "${GREEN}✓${NC} $*"
}

log_error() {
  echo -e "${RED}✗${NC} $*" >&2
}

fail() {
  log_error "$@"
  exit 1
}

# =============================================================================
# INITIALIZATION
# =============================================================================

init_system() {
  log_info "Initializing Backlog Refinement System..."
  echo ""

  # Parse options
  local repo=""
  local github_token="${GITHUB_TOKEN:-}"
  local api_key="${ANTHROPIC_API_KEY:-}"
  local install_skill=1

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --help) show_help; exit 0 ;;
      --repo) repo="$2"; shift 2 ;;
      --token) github_token="$2"; shift 2 ;;
      --api-key) api_key="$2"; shift 2 ;;
      --install-skill) install_skill=1; shift ;;
      --no-install-skill) install_skill=0; shift ;;
      *) shift ;;
    esac
  done

  # Check git repo
  if ! git rev-parse --git-dir > /dev/null 2>&1; then
    fail "Not a git repository. Initialize with 'git init' first."
  fi

  log_success "Found git repository"

  # Auto-detect repo if not specified
  if [[ -z "$repo" ]]; then
    local remote_url
    remote_url=$(git config --get remote.origin.url 2>/dev/null || echo "")
    if [[ -n "$remote_url" ]]; then
      if [[ "$remote_url" =~ github\.com[:/]([^/]+)/(.+)\.git$ ]]; then
        repo="${BASH_REMATCH[1]}/${BASH_REMATCH[2]}"
      fi
    fi
  fi

  if [[ -z "$repo" ]]; then
    fail "Could not auto-detect repository. Use --repo OWNER/REPO"
  fi

  log_success "Repository: $repo"
  echo ""

  # Step 1: Create config directory
  local config_dir="${HOME}/.local"
  local config_file="${config_dir}/refine-backlog.conf"

  if [[ ! -d "$config_dir" ]]; then
    mkdir -p "$config_dir"
    log_success "Created config directory: $config_dir"
  fi

  # Step 2: Create or update config file
  if [[ ! -f "$config_file" ]]; then
    cat > "$config_file" <<CONFIG
# Backlog Refinement System Configuration
# Generated by init-refine-backlog.sh

GITHUB_TOKEN="${github_token}"
ANTHROPIC_API_KEY="${api_key}"
GITHUB_REPO="${repo}"
LOG_LEVEL="info"
ADR_PATTERNS=("docs/adr/ADR-*.md" "adr/*.md")
PLAN_PATTERNS=("planning/*-plan.md" "docs/planning/*-plan.md")
MIN_DAYS_TO_REFINEMENT="28"
BATCH_SIZE="10"
CONFIG
    log_success "Created config file: $config_file"
  else
    log_info "Config file already exists: $config_file"
    log_info "Update it manually if needed"
  fi

  echo ""

  # Step 3: Create CLI symlink
  local bin_dir="${config_dir}/bin"
  if [[ ! -d "$bin_dir" ]]; then
    mkdir -p "$bin_dir"
    log_success "Created bin directory: $bin_dir"
  fi

  local cli_symlink="${bin_dir}/refine-backlog"
  if [[ ! -L "$cli_symlink" ]]; then
    ln -s "${SCRIPT_DIR}/refine-backlog.sh" "$cli_symlink"
    chmod +x "$cli_symlink"
    log_success "Created CLI symlink: $cli_symlink"

    # Suggest adding to PATH
    if ! echo "$PATH" | grep -q "$bin_dir"; then
      log_info "Add to your PATH for easy access:"
      log_info "  export PATH=\"${bin_dir}:\$PATH\""
    fi
  else
    log_info "CLI symlink already exists: $cli_symlink"
  fi

  echo ""

  # Step 4: Initialize refinement log
  local log_file="./refinement-log.json"
  if [[ ! -f "$log_file" ]]; then
    log_info "Initializing refinement log..."

    # Source common.sh to use init_log function
    source "${SCRIPT_DIR}/lib/common.sh"
    source "${SCRIPT_DIR}/lib/log-management.sh"

    init_log "$repo" "$log_file"
    log_success "Created refinement log: $log_file"
  else
    log_info "Refinement log already exists: $log_file"
  fi

  echo ""

  # Step 5: Install Claude skill
  if [[ $install_skill -eq 1 ]]; then
    local skill_src="${SCRIPT_DIR}/skills/refine-backlog.md"
    local skill_dest="${HOME}/.claude/commands/refine-backlog.md"

    if [[ ! -d "${HOME}/.claude/commands" ]]; then
      mkdir -p "${HOME}/.claude/commands"
      log_success "Created Claude commands directory"
    fi

    if [[ -f "$skill_src" ]]; then
      cp "$skill_src" "$skill_dest"
      log_success "Installed Claude skill: $skill_dest"
      log_info "Use it with: /refine-backlog in Claude Code"
    else
      log_error "Skill definition not found: $skill_src"
    fi
  fi

  echo ""

  # Step 6: Update .gitignore
  if [[ -f .gitignore ]]; then
    if ! grep -q "refinement-log.json" .gitignore 2>/dev/null; then
      echo "refinement-log.json.lock" >> .gitignore
      log_success "Added lock file to .gitignore"
    fi
  else
    echo "refinement-log.json.lock" > .gitignore
    log_success "Created .gitignore with lock file"
  fi

  echo ""
  echo "========================================="
  log_success "Initialization complete!"
  echo "========================================="
  echo ""
  log_info "Configuration file:"
  echo "  $config_file"
  echo ""
  log_info "If you haven't set API tokens yet, edit the config file:"
  echo "  Edit: $config_file"
  echo "  Set: GITHUB_TOKEN and ANTHROPIC_API_KEY"
  echo ""
  log_info "Next steps:"
  echo "  1. export PATH=\"${bin_dir}:\$PATH\"  # Or add to .zshrc"
  echo "  2. refine-backlog check               # Check what needs refinement"
  echo "  3. refine-backlog refine --all        # Refine stories with Claude"
  echo ""
}

# =============================================================================
# MAIN
# =============================================================================

init_system "$@"
